###
GET http://localhost:1234/

###
POST http://localhost:1234/
content-type: application/json

{
    "date": "2020-08-20",
    "credits":[{
        "name": "Salário",
        "value": 5000
    }],
    "debits":[{
        "name": "Luz",
        "value": 100,
        "status": "PAGO"
    }]
}