###
GET http://localhost:1234/

###
GET http://localhost:1234/5f483ea0659fd40bf4e726f1

###
POST http://localhost:1234/
content-type: application/json

{
    "date": "2020-09-24",
    "credits":
    [
        {
            "name": "Teste",
            "value": 5000
        },
        {
            "name": "Teste teste",
            "value": 375
        }
    ],
    "debits":
    [
        {
            "name": "Teste Teste teste",
            "value": 100,
            "status": "PAGO"
        }
    ]
}